# Generated by Django 2.0.13 on 2019-06-22 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ('created_date',)},
        ),
    ]
